version: '3.8'

services:
  sb_docker:
    container_name: sb_app
    build: .
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:mysql://java_db:3306/sb_docker?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      java_db:
        condition: service_healthy
  java_db:
    container_name: java_db
    image: mysql:8.0.33
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sb_docker
      MYSQL_PASSWORD: 1234
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10